=== tecnickcom/archive-sourceforge-nicolaasuni/xhtmltranscoder/src/com/tecnick/htmlutils/xhtmltranscoder/config/jxedata.dtd
<!-- JXEDATA
DTD to define HTML/XHTML elements.

Use in JXEDATA: <!DOCTYPE jxedata SYSTEM "jxedata.dtd">

An SGML application conforming to:
- International Standard ISO 8879 Standard Generalized Markup Language, 
- XML (Extensible Markup Language), W3C Recommendation

All JXEDATA element and attribute names must be in lowercase.

Copyright (c) 2004-2005 Tecnick.com S.r.l (www.tecnick.com) Via Ugo Foscolo n.19 - 09045 Quartu Sant'Elena (CA) - ITALY - www.tecnick.com - info@tecnick.com<br/>
License: http://www.gnu.org/copyleft/lesser.html LGPL
@author Nicola Asuni [www.tecnick.com].
@version 1.0

-->

<!ENTITY  lt   "&#38;#60;" >
<!ENTITY  amp  "&#38;#38;" >
<!ENTITY  gt   "&#62;" >
<!ENTITY  apos "&#39;" >
<!ENTITY  quot "&#34;" >


<!--     ELEM                CONTENT                -->
<!--     ATTR       
         NAME                TYPE           DEFAULT -->


<!-- Base Document Element -->
   <!ELEMENT jxedata             (item*) > 
   <!ATTLIST jxedata
         version             CDATA          #FIXED "1.0" >


<!-- Item -->
   <!ELEMENT item            ((item|name|description|category|status|endtag|attributes|dtdtype|type|options|default|icon|intag|outtag|action|keystroke|keymodifier|value)*) >
   <!ATTLIST item
         id                  CDATA          #IMPLIED
         creationdate        CDATA          #IMPLIED
         changedate          CDATA          #IMPLIED >
   
<!-- Name: element name (TMX identifier) -->
   <!ELEMENT name            (#PCDATA)* >
   <!-- No attributes            -->

<!-- Description: element description (TMX identifier) -->
   <!ELEMENT description     (#PCDATA)* >
   <!-- No attributes            -->
   
<!-- Category: element category ID -->
   <!ELEMENT category        (#PCDATA)* >
   <!-- No attributes            -->
   
<!-- Status: element status ID -->
   <!ELEMENT status          (#PCDATA)* >
   <!-- No attributes            -->

<!-- Endtag: false if element is self-closing -->
   <!ELEMENT endtag          (#PCDATA)* >
   <!-- No attributes            -->
   
<!-- Attributes: list of attributes IDs separated by semicolon -->
   <!ELEMENT attributes      (#PCDATA)* >
   <!-- No attributes            -->

<!-- DTD type ID -->
   <!ELEMENT dtdtype         (#PCDATA)* >
   <!-- No attributes            -->
   
<!-- Type: type of input component -->
   <!ELEMENT type            (#PCDATA)* >
   <!-- No attributes            -->
   
<!-- Options: list of selectable values separated by semicolon -->
   <!ELEMENT options         (#PCDATA)* >
   <!-- No attributes            -->
   
<!-- Deafult: default value -->
   <!ELEMENT default         (#PCDATA)* >
   <!-- No attributes            -->

<!-- Icon: button icon -->
   <!ELEMENT icon         (#PCDATA)* >
   <!-- No attributes            -->

<!-- InTag: opening tag to add at the start of selected text when button is pressed-->
   <!ELEMENT intag         (#PCDATA)* >
   <!-- No attributes            -->

<!-- OutTag: closing tag to add at the end of selected text when button is pressed -->
   <!ELEMENT outtag         (#PCDATA)* >
   <!-- No attributes            -->

<!-- KeyStroke: integer number representing the keyboard key to associate to this action  -->
   <!ELEMENT keystroke         (#PCDATA)* >
   <!-- No attributes            -->

<!-- KeyModifier: integer number representing the keyboard modifier key to associate to previous keystroke  -->
   <!ELEMENT keymodifier         (#PCDATA)* >
   <!-- No attributes            -->
   
<!-- Action: button action  -->
   <!ELEMENT action         (#PCDATA)* >
   <!-- No attributes            -->
   
<!-- Value: value associated to the key  -->
   <!ELEMENT value         (#PCDATA)* >
   <!-- No attributes            -->
   
<!-- End -->

=== tecnickcom/archive-sourceforge-nicolaasuni/AIOCP/admin/java/config/status.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE jxedata SYSTEM "jxedata.dtd" [
<!ENTITY % html_entities SYSTEM "html_entities.ent" >
%html_entities;
]>

<!-- 
HTML-XHTML elements status for JXHTMLEDIT

Elements definitions:

item        = status ID
name        = status name
description = status description
-->

<jxedata version="1.0">
	<item id="1">
		<name>general</name>
		<description>tag part of the current standard and not deprecated</description>
	</item>
	<item id="2">
		<name>browser specific</name>
		<description>element specific for a particular browser</description>
	</item>
	<item id="3">
		<name>deprecated</name>
		<description>deprecated element</description>
	</item>
	<item id="4">
		<name>obsolete</name>
		<description>obsolete tag</description>
	</item>
</jxedata>

=== tecnickcom/archive-sourceforge-nicolaasuni/AIOCP/admin/java/config/categories.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE jxedata SYSTEM "jxedata.dtd" [
<!ENTITY % html_entities SYSTEM "html_entities.ent" >
%html_entities;
]>

<!-- 
HTML-XHTML elements categories for JXHTMLEDIT

Elements definitions:

item        = category ID
name        = category name
description = category description
-->

<jxedata version="1.0">
	<item id="1">
		<name>page composition</name>
		<description>tags that describe the main structure of a page</description>
	</item>
	<item id="2">
		<name>page elements</name>
		<description>page elements</description>
	</item>
	<item id="3">
		<name>formatting and layout</name>
		<description>tags that describe the layout and appearance of the elements on a page</description>
	</item>
	<item id="4">
		<name>lists</name>
		<description>tags for the definition of lists</description>
	</item>
	<item id="5">
		<name>forms</name>
		<description>tags to define input forms</description>
	</item>
	<item id="6">
		<name>tables</name>
		<description>tags to define table layout</description>
	</item>
	<item id="7">
		<name>scripting</name>
		<description>tags that define a script or an alternative</description>
	</item>
	<item id="8">
		<name>various</name>
		<description>various tags that not fit other categories</description>
	</item>
</jxedata>
